set(_CATKIN_CURRENT_PACKAGE "drone_application")
set(drone_application_VERSION "0.0.0")
set(drone_application_MAINTAINER "tania <tania@todo.todo>")
set(drone_application_PACKAGE_FORMAT "2")
set(drone_application_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(drone_application_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(drone_application_BUILDTOOL_DEPENDS "catkin")
set(drone_application_BUILDTOOL_EXPORT_DEPENDS )
set(drone_application_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(drone_application_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(drone_application_TEST_DEPENDS )
set(drone_application_DOC_DEPENDS )
set(drone_application_DEPRECATED "")