#!/usr/bin/env python
import rospy
import os
import time
from std_msgs.msg import String
from std_msgs.msg import Empty
from ardrone_autonomy.msg import Navdata

#Status es una numeracion interna de ardrone_driver para indicar el estado del drone
status = -1 
statusList = ["Unknown",
		"Inited",
		"Landed",
		"Flying",
		"Hovering",
		"Test(?)",
		"Taking off",
		"Flying",
		"Landing",
		"Looping"]
def perceive(navdata):
	printStatus(navdata)

def printStatus(navdata):
	status = statusList[navdata.state]
	publisher('Percept',"Status:"+status)
	print "-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-"	
	print "Battery: "+str(navdata.batteryPercent)+"%"
	print "State: "+status
	print "rotX:"+str(navdata.rotX)+" rotY:"+str(navdata.rotY)+" rotZ:"+str(navdata.rotZ)
	print "Altitude: "+str(navdata.altd)
	print "LinX:"+str(navdata.vx)+" LinY:"+str(navdata.vy)+" LinZ:"+str(navdata.vz)
	time.sleep(0.25)
	os.system("clear")
	
def listener():
	rospy.Subscriber('/ardrone/navdata', Navdata, printStatus)
	print("[PERCEP] Listener started")
	rospy.spin()

def publisher(topic,msg):
	pub = rospy.Publisher(topic, String, queue_size=20)
	pub.publish(msg)

if __name__ == '__main__':
        try:
		rospy.init_node('Perception', anonymous=True)
		listener()
        except rospy.ROSInterruptException:
          pass
